[package]
name = "swesource"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libm = "0.2.6"
ndarray = "0.15.0"
netcdf = "0.8.0"
